<h1 style="color: green; ">שיעורי בית 23</h1>

In [51]:
import numpy as np

In [52]:
rng1 = np.arange(1, 11)
rng2 = np.arange(0.5, 5.5, 0.25)
print(rng1)
print(rng2)

[ 1  2  3  4  5  6  7  8  9 10]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.   5.25]


In [53]:
np_zero = np.zeros(10)
np_zero_2 = np.zeros((3, 4))
print(np_zero)
print(np_zero_2)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [54]:
np_linspace = np.linspace(2, 12, 5)
np_linspace_2 = np.linspace(3, 9, 4)
print(np_linspace)
print(np_linspace_2)

[ 2.   4.5  7.   9.5 12. ]
[3. 5. 7. 9.]


In [55]:
np_rand = np.random.rand(2, 4)
print(np_rand)
np_random = np.random.randint(10, 21, (3, 3))
print(np_random)
np_rand_reshape = np_rand.reshape(1, 8)
print(np_rand_reshape)

[[0.80074457 0.96826158 0.31342418 0.69232262]
 [0.87638915 0.89460666 0.08504421 0.03905478]]
[[20 19 18]
 [17 13 16]
 [15 11 19]]
[[0.80074457 0.96826158 0.31342418 0.69232262 0.87638915 0.89460666
  0.08504421 0.03905478]]


### כדי שנוכל להשתמש בפלט של אותם מספרים רנדומליים בקוד שלנו, ושלא יצאו לנו מספרים רנדומליים שונים כשמריצים מחדש את הפונקציה random.rand/it, נשתמש בפונקציה random.seed

In [57]:
### seed example: 
np.random.seed(55)
print(np.random.rand(5, 4))


[[0.09310829 0.97165592 0.48385998 0.2425227 ]
 [0.53112383 0.28554424 0.86263038 0.04110015]
 [0.10834773 0.76716005 0.05142871 0.77571654]
 [0.00913894 0.61831211 0.81870933 0.89858572]
 [0.98561158 0.49674492 0.35231893 0.86708499]]


In [58]:
number_list = []
for _ in range(5):
    number = float(input("enter number"))
    number_list.append(number)

numbers_array = np.array(number_list)
print(numbers_array)
print(f'max number{np.max(numbers_array)}')
print(f'min number{np.min(numbers_array)}')
print(f'array shape{np.shape(numbers_array)}')
print(f'max number index{np.argmax(numbers_array)}')
print(f'min number index{np.argmin(numbers_array)}')


enter number 1
enter number 2
enter number 3
enter number 4
enter number 5


[1. 2. 3. 4. 5.]
max number5.0
min number1.0
array shape(5,)
max number index4
min number index0
